export const projects = [
  {
    title: 'Justclick',
    description: "My responsibility is Established JustClick, an ERP based application from NTI as SaaS software, daily task is facing any challenges to create react with module federation micro Frontend",
      image: '/images/justclick.jpg',
      tags: ['ReactJS', 'Micro FE', 'Storybook','ERP' ],
    id: 0,
  },
  {
    title: 'Livigi',
    description: "Livigi is an online shopping platform for Muslim fashion, providing a unique and diverse range of clothing and accessories that cater to the needs and preferences of customers from the Muslim community.",
      image: '/images/livigi.jpg',
      tags: ['NextJS', 'WebAnalytic', 'eCommerce'],
    visit: 'https://livigisport.com',
    id: 0,
  },
  {
    title: 'HRMS',
    description: "HRMS is an ERP Application that I developed using Odoo framework, this application facilitates all in one solution for helps the HR on doing its Jobdesk. Plus this app is integration with Attendance Biometric Device",
      image: '/images/hrms.png',
      tags: ['Odoo', 'Pyhton', 'ERP'],
    visit: 'https://hrms.berkahmm.com',
    id: 1,
  },
  {
    title: 'HRIS',
    description: "HRIS is an ERP Application that I developed using Odoo framework, this application is present for helps HR to view and manage the information about HR jobdesk. Plus this app is integration with Attendance Biometric Device",
      image: '/images/hris.png',
      tags: ['Odoo', 'Pyhton', 'ERP'],
    visit: 'https://inconis.com',
    id: 2,
  },
  {
    title: 'Musfitatur App',
    description: "MusfitaturApp is a mobile application that I developed using the react native framework, this application facilitates bookings about travel, hajj, umrah.",
      image: '/images/musfiratur.png',
      tags: ['React Native'],
    id: 3,
  },
  {
    title: 'digiSchool',
    description:"digiSchool is a website-based application intended for al izhar schools, made with Nuxt JS, this application contains attendance, and eLearning for students.",
    image: '/images/digischool.png',
    tags: ['Nuxt Js', 'LoopBack 4', 'Node Js'],
    id: 4,
  },
  {
    title: 'eBos',
    description: "eBos is a website for administration and processing of subsidized funds for elementary schools, this application was made using Next JS and Redux Saga",
      image: '/images/ebos.png',
      tags: ['Next Js', 'Redux Saga'],
    id: 5,
  },
  {
    title: 'Smartfren Kiosk Dashboard',
    description: "Kiosk Dashboard is a website for managing smartfren kiosk vending machines, like upgrading the firmware, activating and deactivating vending machines. Built with Angular JS and Loopback 3",
    image: '/images/smartfren.png',
    tags: ['Angular Js', 'Loopback 3', 'Node Js'],
    id: 6,
  },
];

export const personalProjects = [
  {
    title: 'Hackernews Clone',
    description: "Hackernews Clone is my personal project to implemented the Hackernews API in my React JS Project",
      image: '/images/hackernews.png',
      tags: ['React', 'Hackernews API'],
    source: 'https://github.com/azukhrufy/react-hackernews',
    visit: 'https://hackernews.azukhrufy.vercel.app/',
    id: 0,
  },
  {
    title: 'BMI Calc',
    description: "BMI Calc is my personal project during my ios bootcamp with appbrewery on udemy",
      image: '/images/bmicalc.png',
      tags: ['Swift', 'Xcode','Cocoapods'],
    source: 'https://github.com/azukhrufy/BMICalc',
    visit: 'https://github.com/azukhrufy/BMICalc',
    id: 1,
  },
  {
    title: 'Quizzler',
    description: "Quizzler is my personal project during my ios bootcamp with appbrewery on udemy",
      image: '/images/quizzler.png',
      tags: ['Swift', 'Xcode','Cocoapods'],
    source: 'https://github.com/azukhrufy/quizzler',
    visit: 'https://github.com/azukhrufy/quizzler',
    id: 2,
  },
  {
    title: 'To Do App',
    description: "To Do App is my personal project during my ios bootcamp with Robert Petras on udemy",
      image: '/images/todoapp.png',
      tags: ['Swift', 'Xcode','CoreData','SwiftUI'],
    source: 'https://github.com/azukhrufy/iOS-Todo-App',
    visit: 'https://github.com/azukhrufy/iOS-Todo-App',
    id: 3,
  },
  {
    title: 'Catalogue',
    description: "Catalogue is a web app for showing product like fashion etc. Build in Next Js",
      image: '/images/catalogue.png',
      tags: ['React JS', 'Next JS',],
    source: 'https://github.com/azukhrufy/catalogue',
    visit: 'https://azukhrufycatalogue.vercel.app',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey as Software Developer, joined Politeknik Negeri Bandung', },
  { year: 2018, text: 'Funded Proposal for PKM-KC, with application HoTriv (Hotel with 360 view app)', },
  { year: 2018, text: 'Become Head Of MPA HIMAKOM (College Student Legislative Institution', },
  { year: 2018, text: 'Finalist of Kompetisi Mahasiswa Politeknik Nasional (KMIPN) e - Government nomination with Pojok Beasiswa WebApp', },
  { year: 2019, text: 'Funded Proposal for Pekan Kreativitas Mahasiswa PKM-M, with Polban Scholarship Application Website.', },
  { year: 2019, text: 'Started my Internship as Mobile Developer, Created Musfiratur App with using React Native Framework', },
  { year: 2020, text: 'Best Final Project for the Informatics Engineering Diploma at Politeknik Negeri Bandung.', },
  { year: 2020, text: 'Started my Role as Frontend Developer, Created Digischool App with using Nuxt Js, Smartfren Kiosk web with using Angular Js', },
  { year: 2021, text: 'Started my Role as Frontend Developer & Odoo Developer, Involved in HRMS - Odoo, Justclick and Qroi Project with using ReactJS, NextJS, and Odoo, until now.', },
];